program: main_RPS.py
method: bayes
metric:
  goal: minimize
  name: "loss"
parameters:
  dis_max_grad_norm:
    max: 0.4
    min: 0.1
    distribution: uniform
  dis_buffer_size:
    max: 2048
    min: 512
    distribution: int_uniform
  buffer_capacity:
    max: 2048
    min: 512
    distribution: int_uniform
  target_replace:
    max: 200
    min: 50
    distribution: int_uniform
  dis_batch_size:
    max: 128
    min: 32
    distribution: int_uniform
  num_hid_layer:
    max: 2
    min: 1
    distribution: int_uniform
  hidden_size:
    max: 256
    min: 64
    distribution: int_uniform
  batch_size:
    max: 256
    min: 64
    distribution: int_uniform
  alpha_lr:
    max: 0.0002
    min: 0.00005
    distribution: uniform
  rho_lr:
    max: 0.002
    min: 0.0005
    distribution: uniform
  dis_lr:
    max: 0.002
    min: 0.0005
    distribution: uniform
  alpha:
    max: 0.06
    min: 0.015
    distribution: uniform
  c_lr:
    max: 0.0002
    min: 0.00005
    distribution: uniform
  a_lr:
    max: 0.0002
    min: 0.00005
    distribution: uniform
